default_platform(:ios)

import "lanes/release.rb"
import "lanes/tests.rb"

platform :ios do

  desc "Performs a release"
  lane :release do |opts|
    ensure_git_status_clean
    all_tests

    unless opts[:version].nil?
      new_version = opts[:version]
    else
      new_version = get_version_to_release(target: "MockURLResponder")
    end

    start_release_branch(version_number: new_version)
    bump_version(version_number: new_version)
    update_sample_app_carthage_dependency(version_number: new_version)
    end_release_branch(version_number: new_version)

    Dir.chdir("SampleApp") do
      carthage(command: "update")
    end

    test_sample_app
  end

end
