# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Bumps the version"
  lane :update_version do
    version_number = bump_version_depending_on_input
    update_sample_app_carthage_dependency(version_number: version_number)
  end

  private_lane :update_sample_app_carthage_dependency do |opts|
    Dir.chdir("..") do
      File.open('SampleApp/Cartfile', 'w') { |file|
        file.write("github \"joseprl89/MockURLResponder\" \"#{opts[:version_number]}\"")
      }
    end
  end

  private_lane :bump_version_depending_on_input do
    bump_type = UI.input("Please specify the type of bump you want:\n1. patch\n2. minor\n3. major\nSelected: ")
    bump_name = case bump_type
    when "1"
      "patch"
    when "2"
      "minor"
    when "3"
      "major"
    else
      UI.error("Invalid option specified: #{bump_type}")
      throw "Invalid option specified: #{bump_type}"
    end


    version_number = increment_version_number(
      bump_type: bump_name,
      xcodeproj: "MockURLResponder.xcodeproj"
    )
    increment_version_number(
      version_number: version_number,
      xcodeproj: "SampleApp/MockURLResponderSampleApp.xcodeproj"
    )
    #return
    version_number
  end
end
