default_platform(:ios)

import "lanes/release.rb"
import "lanes/tests.rb"

platform :ios do

  desc "Performs a release"
  lane :release do
    ensure_git_status_clean
    tests

    new_version = get_version_to_release
    start_release_branch(version_number: new_version)
    bump_version(version_number: new_version)
    update_sample_app_carthage_dependency(version_number: version_number)
    end_release_branch(version_number: new_version)
  end

end
